#!/usr/bin/env ruby
# change shell bang line.
# programmed by Hiroshi Kimura on 2008-01-01.
# updated: 01-07,

DEBUG=false

def usage
  print <<EOU
usage:
#{__FILE__} --sb /usr/local/bin/ruby *.rb

will rewrite the shell-bang line to #!/usr/local/bin/ruby.
creating backup file whose name will be $original.bak.
except this file.
EOU
  exit(1)
end

def copy(from, to)
  File.open(to,"w") do |fp|
    File.foreach(from) do |line|
      fp.puts(line)
    end
  end
end

def shbang(sb,from,to)
  lines=IO.readlines(from)
  first=nil
  File.open(to,"w") do |fp|
    lines.each do |line|
      if first.nil?
        first=line
        if first=~/^#!/
            fp.puts "#!"+sb
        else
          fp.puts first
        end
      else
        fp.puts line
      end # if first.nil?
    end # lines.each
  end # File.open
end # def shbang

sb=nil
files=Array.new
while (arg=ARGV.shift)
  case arg
  when /--sb/
    sb=ARGV.shift
  when /--/
    usage()
  else # is this neccessary?
    files.push(arg) unless File.basename(__FILE__) =~/#{arg}/
  end
end
usage() if sb.nil?
STDERR.puts files.join("\n") if DEBUG

files.each do |f|
  bak=f+".bak"
  copy(f, bak)
  shbang(sb, bak, f)
end
