isc: yatt.doc yatt.gif
	if [ ! -d /edu/lib/yatt ]; then \
		mkdir /edu/lib/yatt; \
	fi
	cp yatt.doc yatt.gif /edu/lib/yatt/

osx: yatt.doc yatt.gif
	if [ ! -d /Users/hkim/Library/yatt ]; then \
		mkdir /Users/hkim/Library/yatt; \
	fi
	cp yatt.doc yatt.gif /Users/hkim/Library/yatt/

linux: yatt.doc yatt.gif
	if [ ! -d /usr/local/share/yatt ]; then \
		mkdir /usr/local/share/yatt; \
	fi
	cp yatt.doc yatt.gif /usr/local/share/yatt/

clean:
	${RM} *~ .\#*
