#!/usr/bin/env dash
# -*- mode: shell-script -*-
# VERSION: 0.20
# 2009-04-13, change --log destination.
# 2012-04-02, change /bin/sh to /usr/bin/env dash
#             add --db option.
# changed db location from /srv/literacy to /srv/yatt.
# changed log location fro /usr/local/var/log/ to /srv/yatt/log.
# 2012-07-09, migration from sqlite3 to mysql.

/usr/local/yatt/bin/yatt_monitor.rb \
  --hostname localhost \
  --log /dev/null


