#!/bin/sh
#-*- mode: Shell-script -*-
# programmed by Hiroshi Kimura, 2012-04-30.
# updated 2015-03-23.
#
# check whether yatt_monitor alive in a minute.
# if not, restart it.
#

DEST=/opt/local

ps ax | grep yatt_monitor.rb | grep -v 'grep' >/dev/null

case $? in
    1)
	      ${DEST}/bin/yatt_monitor.rb --hostname yatt.melt.kyutech.ac.jp \
	    --log ${DEST}/log/yatt.log
	;;
esac

at -f ${DEST}/bin/yatt_monitor now + 1 minutes
