#!/usr/bin/env dash
# VERSION: 0.13
# 2009-04-13, change --log destination.
# 2012-04-02, change /bin/sh to /usr/bin/env dash
#             add --db option.

/usr/local/bin/yatt_server.rb --hostname edu.melt.kyutech.ac.jp \
    --log /usr/local/var/log/yatt.log \
    --db /srv/literacy/db/yatt.db

